version: '3'

services:
  peer1:
    image: peer
    ports:
      - "8081:8080"
    networks:
      - p2p

  peer2:
    image: peer
    ports:
      - "8082:8080"
    networks:
      - p2p

networks:
  p2p:
    driver: bridge